version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: detectron2_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
